#!/system/bin/sh
# KeyMint is already running when this is invoked. Give binder registration a
# short grace period, then make keystore2 available before earlyBootEnded and
# odsign incur their five-second fallback waits.
sleep 1
setprop ctl.start keystore2
